name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        version: [5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0]
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build swift-${{ matrix.version }}
