name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        version: [4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 5.0.0, 5.0.1, 5.0.2, 5.0.3]
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build swift-${{ matrix.version }}
