name: Docker Image CI

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/docker-image-ci.yml'
      - '*/Dockerfile'
  pull_request:
    paths:
      - '.github/workflows/docker-image-ci.yml'
      - '*/Dockerfile'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        version: [5.2.0, 5.2.1, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.3.0, 5.3.1, 5.3.2]
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build swift-${{ matrix.version }}
